local _, namespace = ...

local RewardsGroup = {
	MIDSUMMER_EVENT = "Midsummer Fire Festival",
}

namespace.DB.rewardCandidiates["midsummer"] = {
	{
		id = "msf-main",
		key = "MSF:Main",
		group = RewardsGroup.MIDSUMMER_EVENT,
		description = "One-time Quests",
		minimumLevel = 1,
		unlockEvent = 341, -- Midsummer Fire Festival
		timeLeft = "end-of-event",
		pick = 8,
		entries = {
			{ quest = 11970, questPool = { 11970, 11971 } }, --The Spinner of Summer Tales
			{ quest = 82087, questPool = { 82087, 82105 } }, -- Torch Tossing
			{ quest = 11657, questPool = { 11657, 11923 } }, -- Torch Catching
			{ quest = 11964, questPool = { 11964, 11966 } }, -- Incense for the Summer Scorchlings
			{ quest = 11886 }, -- Unusual Activity
			{ quest = 11891 }, -- An Innocent Disguise
			{ quest = 12012 }, -- Inform the Elder
			{ quest = 11972 }, -- Shards of Ahune
		},
	},
	{
		id = "msf-daily",
		key = "MSF:Daily",
		group = RewardsGroup.MIDSUMMER_EVENT,
		description = "Daily Quests",
		minimumLevel = 1,
		timeLeft = C_DateAndTime.GetSecondsUntilDailyReset,
		unlockEvent = 341,
		pick = 3,
		entries = {
			{ quest = 82080, questPool = { 82080, 82109 } }, -- More Torch Tossing
			{ quest = 11924, questPool = { 11924, 11925 } }, -- More Torch Catching
			{ quest = 11954, questPool = { 11947, 11948, 11952, 11953, 11954 } }, -- Striking Back
		},
	},
	-- {
	-- 	id = "msf-kal",
	-- 	key = "MSF:Kal",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Kalimdor",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 25,
	-- 	entries = {
	-- 		{ quest = 8654 },
	-- 		{ quest = 8670 },
	-- 		{ quest = 8671 },
	-- 		{ quest = 8672 },
	-- 		{ quest = 8673 },
	-- 		{ quest = 8679 },
	-- 		{ quest = 8680 },
	-- 		{ quest = 8681 },
	-- 		{ quest = 8682 },
	-- 		{ quest = 8684 },
	-- 		{ quest = 8685 },
	-- 		{ quest = 8686 },
	-- 		{ quest = 8715 },
	-- 		{ quest = 8717 },
	-- 		{ quest = 8719 },
	-- 		{ quest = 8720 },
	-- 		{ quest = 8721 },
	-- 		{ quest = 8723 },
	-- 		{ quest = 8724 },
	-- 		{ quest = 8725 },
	-- 		{ quest = 8726 },
	-- 		{ quest = 29739 },
	-- 		{ quest = 29740 },
	-- 		{ quest = 29741 },
	-- 		{ quest = 29742 },
	-- 	},
	-- },
	-- {
	-- 	id = "msf-ek",
	-- 	key = "MSF:E.K.",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Eastern Kingdoms",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 20,
	-- 	entries = {
	-- 		{ quest = 8636 },
	-- 		{ quest = 8642 },
	-- 		{ quest = 8643 },
	-- 		{ quest = 8645 },
	-- 		{ quest = 8647 },
	-- 		{ quest = 8649 },
	-- 		{ quest = 8650 },
	-- 		{ quest = 8651 },
	-- 		{ quest = 8652 },
	-- 		{ quest = 8653 },
	-- 		{ quest = 8674 },
	-- 		{ quest = 8675 },
	-- 		{ quest = 8683 },
	-- 		{ quest = 8688 },
	-- 		{ quest = 8714 },
	-- 		{ quest = 8716 },
	-- 		{ quest = 8722 },
	-- 		{ quest = 29736 },
	-- 		{ quest = 29737 },
	-- 		{ quest = 29738 },
	-- 	},
	-- },
	-- 	{
	-- 	id = "msf-outland",
	-- 	key = "MSF:Outland",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Outland",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 2,
	-- 	entries = {
	-- 		{ quest = 29734 },
	-- 		{ quest = 29735 },
	-- 	},
	-- },
	-- {
	-- 	id = "msf-nr",
	-- 	key = "MSF:Nr",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Northrend",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 18,
	-- 	entries = {
	-- 		{ quest = 13012 },
	-- 		{ quest = 13013 },
	-- 		{ quest = 13014 },
	-- 		{ quest = 13015 },
	-- 		{ quest = 13016 },
	-- 		{ quest = 13018 },
	-- 		{ quest = 13019 },
	-- 		{ quest = 13020 },
	-- 		{ quest = 13024 },
	-- 		{ quest = 13025 },
	-- 		{ quest = 13026 },
	-- 		{ quest = 13027 },
	-- 		{ quest = 13028 },
	-- 		{ quest = 13029 },
	-- 		{ quest = 13030 },
	-- 		{ quest = 13031 },
	-- 		{ quest = 13032 },
	-- 		{ quest = 13033 },
	-- 	},
	-- },
	-- 		{
	-- 	id = "msf-cata",
	-- 	key = "MSF:Cata",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Cataclysm",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 2,
	-- 	entries = {
	-- 		{ quest = 29734 },
	-- 		{ quest = 29735 },
	-- 	},
	-- },
	-- 	{
	-- 	id = "msf-pandaria",
	-- 	key = "MSF:Pandaria",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Pandaria",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 2,
	-- 	entries = {
	-- 		{ quest = 29734 },
	-- 		{ quest = 29735 },
	-- 	},
	-- },
	-- 		{
	-- 	id = "msf-draenor",
	-- 	key = "MSF:Draenor",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Draenor",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 2,
	-- 	entries = {
	-- 		{ quest = 29734 },
	-- 		{ quest = 29735 },
	-- 	},
	-- },
	-- 			{
	-- 	id = "msf-bi",
	-- 	key = "MSF:B.I.",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Broken Isles",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 2,
	-- 	entries = {
	-- 		{ quest = 29734 },
	-- 		{ quest = 29735 },
	-- 	},
	-- },
	-- {
	-- 	id = "msf-kul",
	-- 	key = "MSF:Kul",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Kul Tiras",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 8,
	-- 	entries = {
	-- 		{ quest = 73172 },
	-- 		{ quest = 73716 },
	-- 		{ quest = 73717 },
	-- 		{ quest = 73848 },
	-- 		{ quest = 73858 },
	-- 		{ quest = 73859 },
	-- 		{ quest = 73860 },
	-- 		{ quest = 73861 },
	-- 	},
	-- },
	-- 	{
	-- 	id = "msf-di",
	-- 	key = "MSF:D.I.",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Dragon Isles",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 8,
	-- 	entries = {
	-- 		{ quest = 73172 },
	-- 		{ quest = 73716 },
	-- 		{ quest = 73717 },
	-- 		{ quest = 73848 },
	-- 		{ quest = 73858 },
	-- 		{ quest = 73859 },
	-- 		{ quest = 73860 },
	-- 		{ quest = 73861 },
	-- 	},
	-- },
	-- {
	-- 	id = "msf-ka",
	-- 	key = "MSF:K.A.",
	-- 	group = RewardsGroup.MIDSUMMER_EVENT,
	-- 	description = "Flame Warden of Khaz Algar",
	-- 	minimumLevel = 1,
	-- 	timeLeft = "end-of-event",
	-- 	unlockEvent = 341,
	-- 	pick = 8,
	-- 	entries = {
	-- 		{ quest = 85929 },
	-- 		{ quest = 85930 },
	-- 		{ quest = 85931 },
	-- 		{ quest = 85932 },
	-- 		{ quest = 85933 },
	-- 		{ quest = 85934 },
	-- 		{ quest = 85935 },
	-- 		{ quest = 85936 },
	-- 	},
	-- },
	{
		id = "msf-capital",
		key = "MSF:Capital",
		group = RewardsGroup.MIDSUMMER_EVENT,
		description = "Stealing Frame from faction Capitals",
		minimumLevel = 1,
		timeLeft = "end-of-event",
		unlockEvent = 341,
		pick = 4,
		entries = {
			{ quest = 9330, questPool = { 9330, 9326 } }, -- Stormwind/Undercity
			{ quest = 9331, questPool = { 9331, 9325 } }, -- Ironforge/Thunder Bluff
			{ quest = 9332, questPool = { 9332, 9324 } }, -- Darnassus/Orgrimmar
			{ quest = 11933, questPool = { 11933, 11935 } }, -- Exodar/Silvermoon
		},
	},
	{
		id = "midsummer-boss",
		key = "MSF:Boss",
		group = RewardsGroup.MIDSUMMER_EVENT,
		description = "Daily Dungeon Boss: The Frost Lord Ahune",
		minimumLevel = 10,
		unlockEvent = 341,
		timeLeft = C_DateAndTime.GetSecondsUntilDailyReset,
		entries = {
			{ quest = 286 + 9000000, progressType = 2, dungeon = 286 },
		},
		items = {
			{ item = 117394, amount = 1 },
		},
	},
}
